# Format
# <Branch name> (track name):
#       <standard PID name> : <The name of the variable used for transformation>
# Note: The <standard PID name> should be aligned with the names in the sample configuration file, recommended to not change it.

track_muon: &track_muon
    muplus:
        "ProbNNpi": "ProbNNpi"
        "ProbNNmu": "ProbNNmu"
        "PIDmu": "PIDmu"
    muminus:
        "ProbNNpi": "ProbNNpi"
        "ProbNNmu": "ProbNNmu"
        "PIDmu": "PIDmu"

JKpi: &JKpi
    Kminus:
        "ProbNNk": "ProbNNk"
        "ProbNNpi": "ProbNNpi"
        "ProbNNp": "ProbNNp"

        "PIDK": "PIDK"
        "PIDp": "PIDp"
        "PIDmu": "PIDmu"
    piplus:
        "ProbNNk": "ProbNNk"
        "ProbNNpi": "ProbNNpi"
        "ProbNNp": "ProbNNp"

        "PIDK": "PIDK"
        "PIDp": "PIDp"
        "PIDmu": "PIDmu"

##########################################
MC_Bs2JpsiKstar:
    # mup:
    #     'ProbNNmu'  : 'ProbNNmu'
    #     'PIDmu'     : 'PIDmu'
    # mum:
    #     'ProbNNmu'  : 'ProbNNmu'
    #     'PIDmu'     : 'PIDmu'

    piplus:
        "PIDK": "PIDK"
        "PIDp": "PIDp"

        "ProbNNk": "ProbNNk"
        "ProbNNpi": "ProbNNpi"
        "ProbNNp": "ProbNNp"
        # 'ProbNNpi'  : 'ProbNNpi'

    Kminus:
        "PIDK": "PIDK"
        "PIDp": "PIDp"

        "ProbNNk": "ProbNNk"
        "ProbNNpi": "ProbNNpi"
        "ProbNNp": "ProbNNp"

    # <<: *track_muon
    # <<: *JKpi
